apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ansible-pvc
  namespace: ansible
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: ansible-pv
