apiVersion: v1
kind: PersistentVolume
metadata:
  name: ansible-pv
  namespace: ansible
spec:
  storageClassName: ansible-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 512Mi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/ansible-pv/
