apiVersion: v1
kind: Service
metadata:
  name: ansible
  namespace: ansible
  labels:
    app: ansible
spec:
  type: ClusterIP
  ports:
    - name: ansible
      port: 3000
      targetPort: 3000
      # nodePort: 30336
  selector:
    app: ansible
