apiVersion: v1
kind: Endpoints
metadata:
  name: dahantc-exporter-mod-5gucp-outcluster
  namespace: mod-5gucp
  labels:
    app: dahantc-exporter
subsets:
  - addresses:
      - ip: 172.18.9.190
    ports:
      - name: metrics
        port: 31888
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: dahantc-exporter-mod-5gucp-outcluster
  namespace: mod-5gucp
  labels:
    app: dahantc-exporter
spec:
  ports:
    - port: 80
      targetPort: 31888
      name: metrics
  selector:
    app: dahantc-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dahantc-exporter
  namespace: monitoring
  labels:
    app: dahantc-exporter
spec:
  namespaceSelector:
    matchNames:
      - mod-5gucp
      - rcs-sse
      - monitoring
    # any: true
  selector:
    matchLabels:
      app: dahantc-exporter
  endpoints:
    - port: metrics
      scheme: http
