apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: prometheus
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_from: "273987074@qq.com"
      smtp_smarthost: "smtp.qq.com:465"
      smtp_auth_username: "273987074@qq.com"
      smtp_auth_password: "1"
      smtp_require_tls: false
      smtp_hello: "qq.com"

    route:
      group_by: ["env", "service"]
      group_wait: 10s
      group_interval: 1h
      repeat_interval: 4h
      receiver: "sendsms"
      routes:
        - receiver: "email"
          match_re:
            service: 5gucp_service|5gucp_api
        - receiver: "sendsms"
          match_re:
            service: nginx|redis|minio_server|minio_service|nacos_service|node|mysql

    receivers:
      - name: "sendsms"
        webhook_configs:
          - send_resolved: true
            url: "http://172.18.9.77:19111/api/sendsms"

      - name: "email"
        email_configs:
          - to: "273987074@qq.com"
            send_resolved: true

    inhibit_rules:
      - source_match:
          severity: "严重告警"
        target_match:
          severity: "一般告警"
        equal: ["env", "service"]
