apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-pvc
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: alertmanager-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-pv
  namespace: prometheus
spec:
  storageClassName: alertmanager-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/alertmanager-pv/
---

