apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elk
  labels:
    app: kibana
spec:
  ports:
    - port: 5601
  type: ClusterIP
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elk
  labels:
    app: kibana
spec:
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.12.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: kibana-config
              mountPath: /usr/share/kibana/config/kibana.yml
              readOnly: true
              subPath: kibana.yml
          resources:
            limits:
              cpu: 2000m
              memory: 2G
            requests:
              cpu: 1000m
              memory: 1G
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200
          ports:
            - containerPort: 5601
      volumes:
        - name: kibana-config
          configMap:
            name: kibana
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana
  namespace: elk
  labels:
    k8s-app: kibana
data:
  kibana.yml: |-

    server.name: kibana
    server.host: "0.0.0.0"
    elasticsearch.hosts: [ "http://elasticsearch:9200" ]
    elasticsearch.username: "kibana_system"
    elasticsearch.password: "123456"
    monitoring.ui.container.elasticsearch.enabled: true
    i18n.locale: "zh-CN"
