apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoriametrics-pvc
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: victoriametrics-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: victoriametrics-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: victoriametrics-pv
  local:
    path: /data/victoriametrics-pv/
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: storage-type
              operator: In
              values:
                - local-storage
---

