apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-pv
  namespace: harbor
spec:
  storageClassName: harbor-pv
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 6Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/harbor-pv/
