apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.26.0
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    "global":
      "resolve_timeout": "5m"
      smtp_from: "273987074@qq.com"
      smtp_smarthost: "smtp.qq.com:465"
      smtp_auth_username: "273987074@qq.com"
      smtp_auth_password: "1"
      smtp_require_tls: false
      smtp_hello: "qq.com"
    "inhibit_rules":
    - "equal":
      - "namespace"
      - "alertname"
      "source_matchers":
      - "severity = critical"
      "target_matchers":
      - "severity =~ warning|info"
    - "equal":
      - "namespace"
      - "alertname"
      "source_matchers":
      - "severity = warning"
      "target_matchers":
      - "severity = info"
    - "equal":
      - "namespace"
      "source_matchers":
      - "alertname = InfoInhibitor"
      "target_matchers":
      - "severity = info"
    "receivers":
    - "name": "Default"
    - "name": "Watchdog"
    - "name": "Critical"
    - "name": "null"
    - name: "sendsms"
      webhook_configs:
        - send_resolved: true
          url: "http://172.18.9.77:19111/api/sendsms"
    - name: "email"
      email_configs:
        - to: "273987074@qq.com"
          send_resolved: true
    "route":
      "group_by":
      - "namespace"
      "group_interval": "5m"
      "group_wait": "30s"
      "receiver": "Default"
      "repeat_interval": "12h"
      "routes":
      - "matchers":
        - "alertname = Watchdog"
        "receiver": "Watchdog"
      - "matchers":
        - "alertname = InfoInhibitor"
        "receiver": "null"
      - "matchers":
        - "severity = critical"
        "receiver": "Critical"
      - receiver: "email"
        match_re:
          service: 5gucp_service|5gucp_api
      - receiver: "sendsms"
        match_re:
          service: nginx|redis|minio_server|minio_service|nacos_service|node|mysql
type: Opaque
