apiVersion: apps/v1
kind: Deployment
metadata:
  name: dahantc-exporter
  namespace: mod-5gucp
spec:
  selector:
    matchLabels:
      app: dahantc-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: dahantc-exporter
    spec:
      containers:
        - name: dahantc-exporter
          image: 172.18.1.157/public/dahantc-exporter:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
            - containerPort: 22
              name: ssh
              protocol: TCP
          # volumeMounts:
          #   - name: k8s-config
          #     mountPath: /root/.kube/config
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      # volumes:
      #   - name: k8s-config
      #     hostPath:
      #       path: /root/.kube/config
      #       type: File
      dnsConfig:
        nameservers:
          - 223.5.5.5
---
apiVersion: v1
kind: Service
metadata:
  name: dahantc-exporter
  namespace: mod-5gucp
  labels:
    app: dahantc-exporter
spec:
  ports:
    - port: 80
      targetPort: 80
      name: metrics
  selector:
    app: dahantc-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dahantc-exporter
  namespace: monitoring
  labels:
    app: dahantc-exporter
spec:
  namespaceSelector:
    matchNames:
      - mod-5gucp
      - rcs-sse
    # any: true
  selector:
    matchLabels:
      app: dahantc-exporter
  endpoints:
    - port: metrics
      scheme: http
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: mod-5gucp
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: mod-5gucp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: monitoring
