apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: grafana-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: prometheus
spec:
  storageClassName: grafana-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 512Mi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/grafana-pv/
---

