apiVersion: v1
kind: Service
metadata:
  name: ctc-ema80-app-volvo-svc
  namespace: ema80-ns
spec:
  type: ClusterIP
  ports:
  - port: 8181
    targetPort: 8181
    name: http
  selector:
    app: ctc-ema80-app-volvo-pod
